version: "3.9"
services:
#  daraja_api:
#    build: .
#    environment:
#             DATABASE_NAME: tempdb
#             DB_PASSWORD: Pass@word1
#             DB_USERNAME: sa
#             LOG_LEVEL: INFO
#             DATABASE_SERVER: ms-sql-server
#    ports:
#      - "8089:9000"
#    depends_on:
#      - ms-sql-server

  ms-sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/amd64
    environment:
         ACCEPT_EULA: "Y"
         SA_PASSWORD: "MyPass@word"
         MSSQL_PID: "Developer"
    ports:
        - "1433:1433"
    container_name: ms-sql-server
    hostname: ms-sql-server